#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Aug 29 20:10:49 -03 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto f7584080ab134d789bebf33fd2d18c92 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_ula_behav xil_defaultlib.tb_ula -log elaborate.log"
xelab -wto f7584080ab134d789bebf33fd2d18c92 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_ula_behav xil_defaultlib.tb_ula -log elaborate.log

