#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Sep 23 23:59:40 -04 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 92b9d7b350ad438aa62d9d145e3f3a62 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot decod_tb_behav xil_defaultlib.decod_tb -log elaborate.log"
xelab -wto 92b9d7b350ad438aa62d9d145e3f3a62 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot decod_tb_behav xil_defaultlib.decod_tb -log elaborate.log

