#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Aug 22 21:01:13 -03 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 97fe064c532e4f4fb64bef193d1c3595 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ULA_tb_behav xil_defaultlib.ULA_tb -log elaborate.log"
xelab -wto 97fe064c532e4f4fb64bef193d1c3595 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ULA_tb_behav xil_defaultlib.ULA_tb -log elaborate.log

