#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Aug 22 21:01:14 -03 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ULA_tb_behav -key {Behavioral:sim_1:Functional:ULA_tb} -tclbatch ULA_tb.tcl -view /mnt/nvme0n1p2/Vivado/Vivado_projects/TP3/ULA_behav.wcfg -log simulate.log"
xsim ULA_tb_behav -key {Behavioral:sim_1:Functional:ULA_tb} -tclbatch ULA_tb.tcl -view /mnt/nvme0n1p2/Vivado/Vivado_projects/TP3/ULA_behav.wcfg -log simulate.log

