#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Sep 19 12:19:16 -03 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 7bc1f8b4b20444518faa0a3c80fe26e1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot projeto_1_behav xil_defaultlib.projeto_1 -log elaborate.log"
xelab -wto 7bc1f8b4b20444518faa0a3c80fe26e1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot projeto_1_behav xil_defaultlib.projeto_1 -log elaborate.log

