#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Sep 24 00:00:41 -04 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto f1bc566e36344740b673371567bd794b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot somador_tb_behav xil_defaultlib.somador_tb -log elaborate.log"
xelab -wto f1bc566e36344740b673371567bd794b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot somador_tb_behav xil_defaultlib.somador_tb -log elaborate.log

